name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    - name: Restore Dependencies
      run: dotnet restore src/eShopOnWeb.sln

    - name: Build Solution
      run: dotnet build src/eShopOnWeb.sln --no-restore --configuration Release

    - name: Run Tests
      run: dotnet test src/eShopOnWeb.sln --no-build --configuration Release

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Application
      run: |
        echo "Deploying the application..." 
